#cloud-config
hostname: ubuntu-docker
manage_etc_hosts: true

users:
  - name: nkhan3
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, docker
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHiKd0qHXJDVPHtcWmZhSij83iElLrkckjZI4ce3EmSo homelab-ubuntu-docker

packages:
  - docker.io
  - docker-compose-v2

package_update: true
package_upgrade: true

runcmd:
  - systemctl enable docker --now
  - docker run -d -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
